"""A running API, served from a registry that was really published to.

Nothing is mocked below the HTTP layer: the versions are written by
:class:`backend.app.registry.local.LocalModelRegistry`, the weights are read
back through the loader of section 27 and the summaries are generated by a real
Transformer. Only the tokeniser is faked, because downloading a vocabulary is
the one step that needs a network.

The models are tiny and untrained. What a bout en bout test checks is that a
request reaches the right weights and comes back in the shape the contract
promises; what those weights are worth is measured by the evaluation, on the
frozen test set, and nowhere else.
"""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
import torch
from fastapi.testclient import TestClient

from backend.app.core.config import Settings
from backend.app.inference import loader as loader_module
from backend.app.main import create_app
from backend.app.registry.local import (
    WEIGHTS_PAYLOAD_KEY,
    WEIGHTS_PAYLOAD_VERSION,
    LocalModelRegistry,
)
from backend.app.registry.models import CHAMPION, ModelDraft, ModelSource
from backend.app.schemas import inference as inference_schemas
from src.experiments.config import ScratchModelConfig
from src.models.scratch.transformer import ScratchTransformer

#: Truncation lengths of the fixture corpus, well under the positional budget.
TOKENIZER_BLOCK: dict[str, Any] = {
    "hf_id": "t5-small",
    "source_prefix": "summarize: ",
    "max_source_tokens": 16,
    "max_target_tokens": 8,
}


def architecture(layers: int = 1) -> dict[str, Any]:
    """Return the model block of a Transformer small enough to build in a test.

    Args:
        layers: Depth of both towers, which is what the architecture ablation
            of section 12 varies.

    Returns:
        The block, as an experiment file would declare it.
    """
    return {
        "type": "scratch",
        "d_model": 16,
        "num_heads": 2,
        "encoder_layers": layers,
        "decoder_layers": layers,
        "d_ff": 32,
        "dropout": 0.0,
        "max_position": 32,
        "tie_embeddings": True,
        "norm_first": True,
    }


def write_weights(path: Path, block: dict[str, Any], tokenizer: Any) -> Path:
    """Build a Transformer and write its weights the way publication does.

    Args:
        path: Destination file.
        block: The architecture block the weights must fit.
        tokenizer: The tokeniser sizing the embedding table.

    Returns:
        The path written.
    """
    config = ScratchModelConfig.model_validate(block).architecture(
        vocab_size=len(tokenizer),
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )
    model = ScratchTransformer(config)
    torch.save(
        {"version": WEIGHTS_PAYLOAD_VERSION, WEIGHTS_PAYLOAD_KEY: dict(model.state_dict())}, path
    )
    return path


def draft(name: str, block: dict[str, Any], experiment: str, rouge: float) -> ModelDraft:
    """Describe a version the way ``src.experiments.publish`` describes one."""
    return ModelDraft(
        name=name,
        source=ModelSource.CHECKPOINT,
        architecture=block,
        tokenizer=dict(TOKENIZER_BLOCK),
        experiment=experiment,
        dataset_version="0" * 16,
        git_commit="unknown",
        metrics={"rouge1_f": rouge, "rouge2_f": rouge / 3, "rougeL_f": rouge - 0.01},
        description=f"Version de test issue de {experiment}.",
    )


@pytest.fixture
def registry_root(tmp_path: Path, fake_tokenizer: Any) -> Path:
    """Publish three versions into a registry and return its root.

    The layout mirrors a real deployment: one name holding two versions with the
    newest one served by default, an alias left pointing at the older one, and a
    second name from the architecture ablation.
    """
    root = tmp_path / "registry"
    registry = LocalModelRegistry(root)
    staging = tmp_path / "staging"
    staging.mkdir()

    shallow = architecture(layers=1)
    deep = architecture(layers=2)

    registry.publish(
        draft("scratch", shallow, "scratch_100", 0.20),
        weights=write_weights(staging / "v1.pt", shallow, fake_tokenizer),
    )
    registry.publish(
        draft("scratch", shallow, "scratch_100", 0.22),
        weights=write_weights(staging / "v2.pt", shallow, fake_tokenizer),
        activate=True,
    )
    registry.publish(
        draft("scratch_deep", deep, "scratch_100_layers2", 0.19),
        weights=write_weights(staging / "deep.pt", deep, fake_tokenizer),
    )
    registry.promote(CHAMPION, "scratch", "v1")
    return root


@pytest.fixture
def api(
    registry_root: Path, fake_tokenizer: Any, monkeypatch: pytest.MonkeyPatch
) -> Iterator[TestClient]:
    """Return a client over a started instance serving that registry."""
    settings = Settings(_env_file=None, registry_root=registry_root, max_input_chars=500)
    monkeypatch.setattr(loader_module, "build_tokenizer", lambda hf_id: fake_tokenizer)
    monkeypatch.setattr(inference_schemas, "get_settings", lambda: settings)

    with TestClient(create_app(settings)) as client:
        yield client
